<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IntraDrop</RootNamespace>
    <AssemblyName>IntraDrop</AssemblyName>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.0.1</Version>
    <Company>yunhyok</Company>
    <Product>IntraDrop</Product>
    <Description>인트라넷 파일 전송 트레이 프로그램</Description>
    <SatelliteResourceLanguages>ko</SatelliteResourceLanguages>
  </PropertyGroup>

</Project>
